// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, user_id, type, title, goal, description, progress, start_at, end_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, type, title, goal, description, progress, start_at, end_at, created_at, updated_at
`

type CreateProjectParams struct {
	ID          string
	UserID      string
	Type        string
	Title       string
	Goal        pgtype.Text
	Description pgtype.Text
	Progress    int16
	StartAt     pgtype.Timestamptz
	EndAt       pgtype.Timestamptz
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Goal,
		arg.Description,
		arg.Progress,
		arg.StartAt,
		arg.EndAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Goal,
		&i.Description,
		&i.Progress,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, user_id, type, title, goal, description, progress, start_at, end_at, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Goal,
		&i.Description,
		&i.Progress,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET type = $2,
    title = $3,
    goal = $4,
    description = $5,
    progress = $6,
    start_at = $7,
    end_at = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, type, title, goal, description, progress, start_at, end_at, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          string
	Type        string
	Title       string
	Goal        pgtype.Text
	Description pgtype.Text
	Progress    int16
	StartAt     pgtype.Timestamptz
	EndAt       pgtype.Timestamptz
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Type,
		arg.Title,
		arg.Goal,
		arg.Description,
		arg.Progress,
		arg.StartAt,
		arg.EndAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Goal,
		&i.Description,
		&i.Progress,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
