// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.mut.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id, user_id, project_id, title, description, estimated_minutes, actual_minutes, progress,
    priority, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, project_id, title, description, estimated_minutes, actual_minutes, progress,
          priority, status, created_at, updated_at
`

type CreateTaskParams struct {
	ID               string
	UserID           string
	ProjectID        pgtype.Text
	Title            string
	Description      pgtype.Text
	EstimatedMinutes pgtype.Int4
	ActualMinutes    pgtype.Int4
	Progress         int16
	Priority         string
	Status           string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.EstimatedMinutes,
		arg.ActualMinutes,
		arg.Progress,
		arg.Priority,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.EstimatedMinutes,
		&i.ActualMinutes,
		&i.Progress,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET user_id = $2,
    project_id = $3,
    title = $4,
    description = $5,
    estimated_minutes = $6,
    actual_minutes = $7,
    progress = $8,
    priority = $9,
    status = $10,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, project_id, title, description, estimated_minutes, actual_minutes, progress,
          priority, status, created_at, updated_at
`

type UpdateTaskParams struct {
	ID               string
	UserID           string
	ProjectID        pgtype.Text
	Title            string
	Description      pgtype.Text
	EstimatedMinutes pgtype.Int4
	ActualMinutes    pgtype.Int4
	Progress         int16
	Priority         string
	Status           string
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.EstimatedMinutes,
		arg.ActualMinutes,
		arg.Progress,
		arg.Priority,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.EstimatedMinutes,
		&i.ActualMinutes,
		&i.Progress,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
