// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.query.sql

package sqlc

import (
	"context"
)

const getTask = `-- name: GetTask :one
SELECT id, user_id, project_id, title, description, estimated_minutes, actual_minutes, progress,
       priority, status, created_at, updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.EstimatedMinutes,
		&i.ActualMinutes,
		&i.Progress,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByFrequency = `-- name: GetTaskByFrequency :many
SELECT t.id, t.user_id, t.project_id, t.title, t.description, t.estimated_minutes, t.actual_minutes, t.progress,
       t.priority, t.status, t.created_at, t.updated_at
FROM tasks AS t
WHERE EXISTS (
    SELECT 1
    FROM todo_items AS ti
    JOIN todo_item_frequencies AS tif ON tif.todo_item_id = ti.id
    WHERE ti.task_id = t.id
      AND tif.frequency = $1::text
)
OR EXISTS (
    SELECT 1
    FROM task_schedules AS ts
    JOIN task_schedule_frequencies AS tsf ON tsf.task_schedule_id = ts.id
    WHERE ts.task_id = t.id
      AND tsf.frequency = $1::text
)
`

func (q *Queries) GetTaskByFrequency(ctx context.Context, frequency string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByFrequency, frequency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Progress,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByPriority = `-- name: GetTaskByPriority :many
SELECT id, user_id, project_id, title, description, estimated_minutes, actual_minutes, progress,
       priority, status, created_at, updated_at
FROM tasks
WHERE priority = $1
`

func (q *Queries) GetTaskByPriority(ctx context.Context, priority string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByPriority, priority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Progress,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByProject = `-- name: GetTaskByProject :many
SELECT id, user_id, project_id, title, description, estimated_minutes, actual_minutes, progress,
       priority, status, created_at, updated_at
FROM tasks
WHERE project_id = $1::text
`

func (q *Queries) GetTaskByProject(ctx context.Context, projectID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Progress,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByProjectType = `-- name: GetTaskByProjectType :many
SELECT t.id, t.user_id, t.project_id, t.title, t.description, t.estimated_minutes, t.actual_minutes, t.progress,
       t.priority, t.status, t.created_at, t.updated_at
FROM tasks AS t
JOIN projects AS p ON p.id = t.project_id
WHERE p.type = $1
`

func (q *Queries) GetTaskByProjectType(ctx context.Context, type_ string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByProjectType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Progress,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByStatus = `-- name: GetTaskByStatus :many
SELECT id, user_id, project_id, title, description, estimated_minutes, actual_minutes, progress,
       priority, status, created_at, updated_at
FROM tasks
WHERE status = $1
`

func (q *Queries) GetTaskByStatus(ctx context.Context, status string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Progress,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByTag = `-- name: GetTaskByTag :many
SELECT t.id, t.user_id, t.project_id, t.title, t.description, t.estimated_minutes, t.actual_minutes, t.progress,
       t.priority, t.status, t.created_at, t.updated_at
FROM tasks AS t
JOIN task_tag_assignments AS tta ON tta.task_id = t.id
WHERE tta.tag_id = $1
`

func (q *Queries) GetTaskByTag(ctx context.Context, tagID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Progress,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
