// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo_lists.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTodoListItem = `-- name: AddTodoListItem :one
INSERT INTO todo_list_items (todo_list_id, todo_item_id, position)
VALUES ($1, $2, $3)
RETURNING todo_list_id, todo_item_id, position, created_at
`

type AddTodoListItemParams struct {
	TodoListID string
	TodoItemID string
	Position   int32
}

func (q *Queries) AddTodoListItem(ctx context.Context, arg AddTodoListItemParams) (TodoListItem, error) {
	row := q.db.QueryRow(ctx, addTodoListItem, arg.TodoListID, arg.TodoItemID, arg.Position)
	var i TodoListItem
	err := row.Scan(
		&i.TodoListID,
		&i.TodoItemID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const addTodoListTaskSchedule = `-- name: AddTodoListTaskSchedule :one
INSERT INTO todo_list_task_schedules (todo_list_id, task_schedule_id)
VALUES ($1, $2)
RETURNING todo_list_id, task_schedule_id, created_at
`

type AddTodoListTaskScheduleParams struct {
	TodoListID     string
	TaskScheduleID string
}

func (q *Queries) AddTodoListTaskSchedule(ctx context.Context, arg AddTodoListTaskScheduleParams) (TodoListTaskSchedule, error) {
	row := q.db.QueryRow(ctx, addTodoListTaskSchedule, arg.TodoListID, arg.TaskScheduleID)
	var i TodoListTaskSchedule
	err := row.Scan(&i.TodoListID, &i.TaskScheduleID, &i.CreatedAt)
	return i, err
}

const createTodoList = `-- name: CreateTodoList :one
INSERT INTO todo_lists (id, user_id, list_date)
VALUES ($1, $2, $3)
RETURNING id, user_id, list_date, created_at, updated_at
`

type CreateTodoListParams struct {
	ID       string
	UserID   string
	ListDate pgtype.Date
}

func (q *Queries) CreateTodoList(ctx context.Context, arg CreateTodoListParams) (TodoList, error) {
	row := q.db.QueryRow(ctx, createTodoList, arg.ID, arg.UserID, arg.ListDate)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ListDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodoList = `-- name: DeleteTodoList :exec
DELETE FROM todo_lists
WHERE id = $1
`

func (q *Queries) DeleteTodoList(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTodoList, id)
	return err
}

const getTodoList = `-- name: GetTodoList :one
SELECT id, user_id, list_date, created_at, updated_at
FROM todo_lists
WHERE id = $1
`

func (q *Queries) GetTodoList(ctx context.Context, id string) (TodoList, error) {
	row := q.db.QueryRow(ctx, getTodoList, id)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ListDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodoListByUserAndDate = `-- name: GetTodoListByUserAndDate :one
SELECT id, user_id, list_date, created_at, updated_at
FROM todo_lists
WHERE user_id = $1
  AND list_date = $2
`

type GetTodoListByUserAndDateParams struct {
	UserID   string
	ListDate pgtype.Date
}

func (q *Queries) GetTodoListByUserAndDate(ctx context.Context, arg GetTodoListByUserAndDateParams) (TodoList, error) {
	row := q.db.QueryRow(ctx, getTodoListByUserAndDate, arg.UserID, arg.ListDate)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ListDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTodoListItems = `-- name: ListTodoListItems :many
SELECT todo_list_id, todo_item_id, position, created_at
FROM todo_list_items
WHERE todo_list_id = $1
ORDER BY position ASC
`

func (q *Queries) ListTodoListItems(ctx context.Context, todoListID string) ([]TodoListItem, error) {
	rows, err := q.db.Query(ctx, listTodoListItems, todoListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoListItem
	for rows.Next() {
		var i TodoListItem
		if err := rows.Scan(
			&i.TodoListID,
			&i.TodoItemID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoListTaskSchedules = `-- name: ListTodoListTaskSchedules :many
SELECT tlts.todo_list_id, tlts.task_schedule_id, tlts.created_at
FROM todo_list_task_schedules AS tlts
JOIN task_schedules AS ts ON ts.id = tlts.task_schedule_id
WHERE tlts.todo_list_id = $1
ORDER BY ts.start_at ASC
`

func (q *Queries) ListTodoListTaskSchedules(ctx context.Context, todoListID string) ([]TodoListTaskSchedule, error) {
	rows, err := q.db.Query(ctx, listTodoListTaskSchedules, todoListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoListTaskSchedule
	for rows.Next() {
		var i TodoListTaskSchedule
		if err := rows.Scan(&i.TodoListID, &i.TaskScheduleID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoListsByUser = `-- name: ListTodoListsByUser :many
SELECT id, user_id, list_date, created_at, updated_at
FROM todo_lists
WHERE user_id = $1
ORDER BY list_date DESC
`

func (q *Queries) ListTodoListsByUser(ctx context.Context, userID string) ([]TodoList, error) {
	rows, err := q.db.Query(ctx, listTodoListsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoList
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ListDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTodoListItem = `-- name: RemoveTodoListItem :exec
DELETE FROM todo_list_items
WHERE todo_list_id = $1
  AND todo_item_id = $2
`

type RemoveTodoListItemParams struct {
	TodoListID string
	TodoItemID string
}

func (q *Queries) RemoveTodoListItem(ctx context.Context, arg RemoveTodoListItemParams) error {
	_, err := q.db.Exec(ctx, removeTodoListItem, arg.TodoListID, arg.TodoItemID)
	return err
}

const removeTodoListTaskSchedule = `-- name: RemoveTodoListTaskSchedule :exec
DELETE FROM todo_list_task_schedules
WHERE todo_list_id = $1
  AND task_schedule_id = $2
`

type RemoveTodoListTaskScheduleParams struct {
	TodoListID     string
	TaskScheduleID string
}

func (q *Queries) RemoveTodoListTaskSchedule(ctx context.Context, arg RemoveTodoListTaskScheduleParams) error {
	_, err := q.db.Exec(ctx, removeTodoListTaskSchedule, arg.TodoListID, arg.TaskScheduleID)
	return err
}

const updateTodoListItemPosition = `-- name: UpdateTodoListItemPosition :one
UPDATE todo_list_items
SET position = $3
WHERE todo_list_id = $1
  AND todo_item_id = $2
RETURNING todo_list_id, todo_item_id, position, created_at
`

type UpdateTodoListItemPositionParams struct {
	TodoListID string
	TodoItemID string
	Position   int32
}

func (q *Queries) UpdateTodoListItemPosition(ctx context.Context, arg UpdateTodoListItemPositionParams) (TodoListItem, error) {
	row := q.db.QueryRow(ctx, updateTodoListItemPosition, arg.TodoListID, arg.TodoItemID, arg.Position)
	var i TodoListItem
	err := row.Scan(
		&i.TodoListID,
		&i.TodoItemID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
