// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodoItem = `-- name: CreateTodoItem :one
INSERT INTO todo_items (id, task_id, title, completed, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, task_id, title, completed, position, created_at, updated_at
`

type CreateTodoItemParams struct {
	ID        string
	TaskID    string
	Title     string
	Completed bool
	Position  int32
}

type CreateTodoItemRow struct {
	ID        string
	TaskID    string
	Title     string
	Completed bool
	Position  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateTodoItem(ctx context.Context, arg CreateTodoItemParams) (CreateTodoItemRow, error) {
	row := q.db.QueryRow(ctx, createTodoItem,
		arg.ID,
		arg.TaskID,
		arg.Title,
		arg.Completed,
		arg.Position,
	)
	var i CreateTodoItemRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Completed,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodoItem = `-- name: DeleteTodoItem :exec
DELETE FROM todo_items
WHERE id = $1
`

func (q *Queries) DeleteTodoItem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTodoItem, id)
	return err
}

const getTodoItem = `-- name: GetTodoItem :one
SELECT id, task_id, title, completed, position, created_at, updated_at
FROM todo_items
WHERE id = $1
`

type GetTodoItemRow struct {
	ID        string
	TaskID    string
	Title     string
	Completed bool
	Position  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetTodoItem(ctx context.Context, id string) (GetTodoItemRow, error) {
	row := q.db.QueryRow(ctx, getTodoItem, id)
	var i GetTodoItemRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Completed,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodoItem = `-- name: UpdateTodoItem :one
UPDATE todo_items
SET task_id = $2,
    title = $3,
    completed = $4,
    position = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, task_id, title, completed, position, created_at, updated_at
`

type UpdateTodoItemParams struct {
	ID        string
	TaskID    string
	Title     string
	Completed bool
	Position  int32
}

type UpdateTodoItemRow struct {
	ID        string
	TaskID    string
	Title     string
	Completed bool
	Position  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateTodoItem(ctx context.Context, arg UpdateTodoItemParams) (UpdateTodoItemRow, error) {
	row := q.db.QueryRow(ctx, updateTodoItem,
		arg.ID,
		arg.TaskID,
		arg.Title,
		arg.Completed,
		arg.Position,
	)
	var i UpdateTodoItemRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Completed,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
